# Generated by Django 5.1.15 on 2026-09-23 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civiles',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de sangre',
                'verbose_name_plural': 'Tipos de sangre',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('last_name_paternal', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('last_name_maternal', models.CharField(blank=True, help_text='Puede quedar vacío — no todas las personas lo tienen.', max_length=100, verbose_name='Apellido materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nss', models.CharField(max_length=11, unique=True, verbose_name='NSS')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('birth_place_state', models.CharField(blank=True, max_length=100, verbose_name='Estado de nacimiento')),
                ('has_children', models.BooleanField(default=False, verbose_name='Tiene hijos')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo personal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.escolaridad', verbose_name='Escolaridad')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.genero', verbose_name='Género')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.estadocivil', verbose_name='Estado civil')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persons_persona',
                'ordering': ['last_name_paternal', 'last_name_maternal', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactoUrgencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('relationship', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_urgencia', to='persons.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Contacto de urgencia',
                'verbose_name_plural': 'Contactos de urgencia',
            },
        ),
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to='persons.persona', verbose_name='Persona')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.tiposangre', verbose_name='Tipo de sangre')),
            ],
            options={
                'verbose_name': 'Perfil médico',
                'verbose_name_plural': 'Perfiles médicos',
            },
        ),
    ]
