# Generated by Django 5.1.15 on 2026-09-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nss',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
    ]
