# Generated by Django 5.1.15 on 2026-09-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_persona_birth_date_alter_persona_curp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persons.genero', verbose_name='Género'),
        ),
    ]
