# Generated by Django 5.1.15 on 2026-10-01 18:29

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0007_tiporequisicion_requiere_justificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_terminal', models.BooleanField(default=False, help_text='Una Posición no puede tener dos Requisición abiertas (no terminales) a la vez.', verbose_name='Es un estado final')),
            ],
            options={
                'verbose_name': 'Estado de requisición',
                'verbose_name_plural': 'Estados de requisición',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtapaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Etapa de aprobación',
                'verbose_name_plural': 'Etapas de aprobación',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioACubrir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario a cubrir',
                'verbose_name_plural': 'Horarios a cubrir',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoContratoOfrecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de contrato ofrecido',
                'verbose_name_plural': 'Tipos de contrato ofrecido',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud')),
                ('fecha_a_cubrir_vacante', models.DateField(blank=True, null=True, verbose_name='Fecha a cubrir la vacante')),
                ('fecha_entrega_a_capital_humano', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega a Capital Humano')),
                ('area_solicitante', models.CharField(blank=True, help_text='El departamento que pide cubrir la plaza -- NO es Posicion.area (esa es la ubicación física).', max_length=150, verbose_name='Área solicitante')),
                ('justificacion', models.TextField(blank=True, help_text='Obligatoria solo si TipoRequisicion.requiere_justificacion está marcado para el Tipo elegido.', verbose_name='Justificación de la requisición')),
                ('idiomas_requeridos', models.CharField(blank=True, max_length=150, verbose_name='Idiomas')),
                ('disposicion_viajar', models.BooleanField(blank=True, default=None, help_text="Sin marcar mientras no se sepa -- no forzar 'No' cuando el dato no se ha capturado.", null=True, verbose_name='Disposición para viajar')),
                ('nivel_tabulador', models.CharField(blank=True, max_length=50, verbose_name='Nivel de tabulador')),
                ('sueldo_mensual_compuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo mensual compuesto')),
                ('sueldo_mensual_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo mensual bruto')),
                ('sueldo_mensual_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sueldo mensual neto')),
                ('motivo_suspension', models.TextField(blank=True, verbose_name='Motivo de suspensión')),
                ('fecha_suspension', models.DateField(blank=True, null=True, verbose_name='Fecha de suspensión')),
                ('autorizado_por_suspension', models.CharField(blank=True, max_length=150, verbose_name='Autorizado por (suspensión)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.estadorequisicion', verbose_name='Estado')),
                ('horario_a_cubrir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.horarioacubrir', verbose_name='Horario a cubrir')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones', to='positions.posicion', verbose_name='Posición')),
                ('tipo', models.ForeignKey(help_text='Reemplazo o Nueva Posición -- propio de esta Requisición, no de la Posición.', on_delete=django.db.models.deletion.PROTECT, to='positions.tiporequisicion', verbose_name='Tipo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_contrato_ofrecido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.tipocontratoofrecido', verbose_name='Tipo de contrato')),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'ordering': ['-fecha_solicitud'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AprobacionRequisicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, help_text='Vacío = pendiente.', null=True, verbose_name='Fecha de aprobación')),
                ('nombre_manual', models.CharField(blank=True, help_text='Si la firma fue física, fuera del sistema.', max_length=150, verbose_name='Nombre capturado a mano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Si se aceptó dentro del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_requisicion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que aprobó')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.etapaaprobacion', verbose_name='Etapa')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='recruitment.requisicion', verbose_name='Requisición')),
            ],
            options={
                'verbose_name': 'Aprobación de requisición',
                'verbose_name_plural': 'Aprobaciones de requisición',
                'ordering': ['etapa__name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('requisicion', 'etapa'), name='unique_etapa_por_requisicion')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
