# Generated by Django 5.1.15 on 2026-10-02 15:07

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_persona_gender'),
        ('positions', '0007_tiporequisicion_requiere_justificacion'),
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaConductual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Competencia conductual',
                'verbose_name_plural': 'Competencias conductuales',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiasPorLaborar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Días por laborar',
                'verbose_name_plural': 'Días por laborar',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RangoEdad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Rango de edad',
                'verbose_name_plural': 'Rangos de edad',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecursoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Recurso asignado',
                'verbose_name_plural': 'Recursos asignados',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requiere_persona', models.BooleanField(default=False, help_text='La conformidad se registra a nombre de una Persona (ej. el Colaborador que ocupa la Posición).', verbose_name='Requiere una persona específica')),
            ],
            options={
                'verbose_name': 'Rol de conformidad',
                'verbose_name_plural': 'Roles de conformidad',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptivoPuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0, editable=False, help_text='Se asigna sola al crear: 1, 2, 3... por Posición.', verbose_name='Versión')),
                ('congelado_en', models.DateTimeField(blank=True, editable=False, help_text='Vacío = borrador editable. Con fecha = versión aprobada, inmutable.', null=True, verbose_name='Congelado el')),
                ('nombre_puesto', models.CharField(blank=True, max_length=150, verbose_name='Nombre del puesto')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('area_departamento', models.CharField(blank=True, max_length=150, verbose_name='Área / Departamento')),
                ('reporta_a', models.CharField(blank=True, max_length=150, verbose_name='Reporta a')),
                ('supervisa_a', models.TextField(blank=True, help_text='Puestos y número de personas a cargo, si aplica.', verbose_name='Supervisa a')),
                ('fecha_elaboracion', models.DateField(verbose_name='Fecha de elaboración / actualización')),
                ('edad_otro', models.CharField(blank=True, max_length=100, verbose_name='Edad (otro)')),
                ('disponibilidad_viajar', models.BooleanField(blank=True, default=None, help_text="Sin marcar mientras no se sepa -- no forzar 'No'.", null=True, verbose_name='Disponibilidad para viajar')),
                ('dias_por_laborar_otro', models.CharField(blank=True, max_length=100, verbose_name='Días por laborar (otro)')),
                ('horario_otro', models.CharField(blank=True, max_length=100, verbose_name='Horario (otro)')),
                ('proposito', models.TextField(blank=True, verbose_name='Propósito del puesto')),
                ('decisiones_operativas', models.TextField(blank=True, verbose_name='Decisiones operativas')),
                ('decisiones_funcionales', models.TextField(blank=True, verbose_name='Decisiones funcionales')),
                ('decisiones_estrategicas', models.TextField(blank=True, verbose_name='Decisiones estratégicas')),
                ('relaciones_internas', models.TextField(blank=True, verbose_name='Relaciones internas')),
                ('relaciones_externas', models.TextField(blank=True, verbose_name='Relaciones externas')),
                ('escolaridad_minima', models.TextField(blank=True, verbose_name='Escolaridad mínima')),
                ('experiencia_requerida', models.TextField(blank=True, verbose_name='Experiencia requerida')),
                ('idiomas', models.TextField(blank=True, verbose_name='Idiomas')),
                ('competencias_tecnicas', models.TextField(blank=True, verbose_name='Competencias y/o habilidades técnicas')),
                ('competencias_otras', models.CharField(blank=True, max_length=255, verbose_name='Otras competencias')),
                ('recursos_otro', models.CharField(blank=True, max_length=255, verbose_name='Otros recursos')),
                ('competencias', models.ManyToManyField(blank=True, related_name='+', to='recruitment.competenciaconductual', verbose_name='Competencias')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.horarioacubrir', verbose_name='Horario por cubrir')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptivos', to='positions.posicion', verbose_name='Posición')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('dias_por_laborar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.diasporlaborar', verbose_name='Días por laborar')),
                ('edad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.rangoedad', verbose_name='Edad')),
                ('recursos', models.ManyToManyField(blank=True, related_name='+', to='recruitment.recursoasignado', verbose_name='Recursos necesarios')),
            ],
            options={
                'verbose_name': 'Descriptivo de puesto',
                'verbose_name_plural': 'Descriptivos de puesto',
                'ordering': ['posicion', '-version'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConformidadDescriptivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha', models.DateField(blank=True, help_text='Vacío = pendiente.', null=True, verbose_name='Fecha de conformidad')),
                ('nombre_manual', models.CharField(blank=True, help_text='Si la firma fue física, fuera del sistema.', max_length=150, verbose_name='Nombre capturado a mano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conformidades_descriptivo', to='persons.persona', verbose_name='Persona')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Si aceptó dentro del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformidades_descriptivo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que aceptó')),
                ('descriptivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conformidades', to='recruitment.descriptivopuesto', verbose_name='Descriptivo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.rolconformidad', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Conformidad de descriptivo',
                'verbose_name_plural': 'Conformidades de descriptivo',
                'ordering': ['rol__name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FuncionPuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('descriptivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='recruitment.descriptivopuesto', verbose_name='Descriptivo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Función del puesto',
                'verbose_name_plural': 'Funciones del puesto',
                'ordering': ['orden'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('descriptivo', 'orden'), name='unique_orden_funcion_por_descriptivo')],
            },
        ),
        migrations.CreateModel(
            name='IndicadorDesempeno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Número')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('descriptivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='recruitment.descriptivopuesto', verbose_name='Descriptivo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indicador de desempeño',
                'verbose_name_plural': 'Indicadores de desempeño',
                'ordering': ['orden'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('descriptivo', 'orden'), name='unique_orden_indicador_por_descriptivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='descriptivopuesto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('posicion', 'version'), name='unique_version_descriptivo_por_posicion'),
        ),
        migrations.AddConstraint(
            model_name='descriptivopuesto',
            constraint=models.UniqueConstraint(condition=models.Q(('congelado_en__isnull', True), ('is_deleted', False)), fields=('posicion',), name='unique_borrador_descriptivo_por_posicion'),
        ),
        migrations.AddConstraint(
            model_name='conformidaddescriptivo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('persona__isnull', False)), fields=('descriptivo', 'rol', 'persona'), name='unique_conformidad_por_persona_y_rol'),
        ),
        migrations.AddConstraint(
            model_name='conformidaddescriptivo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('persona__isnull', True)), fields=('descriptivo', 'rol'), name='unique_conformidad_sin_persona_por_rol'),
        ),
    ]
