# Generated by Django 5.1.15 on 2026-10-02 17:43

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_descriptivo_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionNuevaPosicion',
            fields=[
            ],
            options={
                'verbose_name': 'Requisición de Nueva Posición',
                'verbose_name_plural': 'Requisiciones de Nueva Posición',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recruitment.requisicion',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionReemplazo',
            fields=[
            ],
            options={
                'verbose_name': 'Requisición de Reemplazo',
                'verbose_name_plural': 'Requisiciones de Reemplazo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recruitment.requisicion',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
