# Generated by Django 5.1.15 on 2026-09-23 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0003_alter_tenant_options'),
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceDePosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Alcance de posición',
                'verbose_name_plural': 'Alcances de posición',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estatus de posición',
                'verbose_name_plural': 'Estatus de posición',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de posición',
                'verbose_name_plural': 'Tipos de posición',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de requisición',
                'verbose_name_plural': 'Tipos de requisición',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_registro_vacante', models.DateField(blank=True, null=True, verbose_name='Fecha de registro de vacante')),
                ('fecha_autorizacion_vacante', models.DateField(blank=True, null=True, verbose_name='Fecha de autorización de vacante')),
                ('headhunter', models.CharField(blank=True, max_length=150, verbose_name='Headhunter')),
                ('solicitante_vacante', models.CharField(blank=True, max_length=150, verbose_name='Solicitante de vacante')),
                ('proyecto_eventual', models.CharField(blank=True, max_length=150, verbose_name='Proyecto eventual')),
                ('fecha_esperada_termino', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de término')),
                ('alcance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.alcancedeposicion', verbose_name='Alcance de posición')),
                ('area', models.ForeignKey(help_text='Dónde está sentada físicamente (Ubicación → Nave → Área).', on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='locations.area', verbose_name='Área')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='positions.estatusposicion', verbose_name='Estatus')),
                ('genero_requerido', models.ForeignKey(blank=True, help_text='Requisito de la vacante, no el género de quien la ocupe.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.genero', verbose_name='Género requerido')),
                ('organization_node', models.ForeignKey(help_text='A qué Unidad de Negocio/Empresa pertenece esta posición.', on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='organizations.organizationnode', verbose_name='Unidad organizacional')),
                ('reports_to', models.ForeignKey(blank=True, help_text='La posición de la que depende — de aquí se resuelve el jefe inmediato.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='positions.posicion', verbose_name='Reporta a')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='positions.puesto', verbose_name='Puesto')),
                ('tipo_posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.tipoposicion', verbose_name='Tipo de posición')),
                ('tipo_requisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.tiporequisicion', verbose_name='Tipo de requisición')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
    ]
