# Generated by Django 5.1.15 on 2026-09-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Dónde está sentada físicamente (Ubicación → Nave → Área).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='locations.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='positions.puesto', verbose_name='Puesto'),
        ),
    ]
