# Generated by Django 5.1.15 on 2026-09-24 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_posicion_area_alter_posicion_puesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReportaA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField(verbose_name='Vigente desde')),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = periodo actual.', null=True, verbose_name='Vigente hasta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reporta_a', to='positions.posicion', verbose_name='Posición')),
                ('reports_to', models.ForeignKey(blank=True, help_text='Vacío significa que en este periodo no reportaba a nadie (nivel más alto).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_subordinados', to='positions.posicion', verbose_name='Reportaba a')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de a quién reporta',
                'verbose_name_plural': 'Historial de a quién reporta',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('posicion',), name='unique_historial_reporta_a_vigente_por_posicion')],
            },
        ),
    ]
