# Generated by Django 5.1.15 on 2026-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_historialreportaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='supervision_texto',
            field=models.CharField(blank=True, help_text='Tal como viene en la sábana — puede ser un nombre de persona o de unidad, todavía sin confirmar.', max_length=200, verbose_name='Supervisión (texto original)'),
        ),
    ]
