# Generated by Django 5.1.15 on 2026-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_posicion_supervision_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='es_gerencia_de_unidad',
            field=models.BooleanField(default=False, help_text='Quien ocupe una Posición con este Puesto es automáticamente el jefe de todas las demás Posiciones de su misma Unidad de Negocio y Ubicación física. Déjalo desmarcado salvo que GPA haya confirmado que este Puesto específico cumple ese rol.', verbose_name='Es gerencia de la unidad'),
        ),
    ]
