# Generated by Django 5.1.15 on 2026-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0006_historialpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporequisicion',
            name='requiere_justificacion',
            field=models.BooleanField(default=False, verbose_name='Requiere justificación'),
        ),
    ]
