# Generated by Django 5.1.15 on 2026-09-21 21:01

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=40, verbose_name='ID del objeto')),
                ('file', models.FileField(upload_to=apps.core.models._attachment_upload_path, verbose_name='Archivo')),
                ('filename', models.CharField(blank=True, help_text='Se auto-completa con el nombre del archivo subido.', max_length=255, verbose_name='Nombre del archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
