# Generated by Django 5.1.15 on 2026-09-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_documenttype_attachment_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(help_text='A qué tabla del sistema se engancha este archivo (ej. una persona, un puesto). Técnico: normalmente se llena solo desde la ficha de esa entidad, no se elige aquí a mano.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(db_index=True, help_text='ID del registro específico: UUID para entidades operativas, número para catálogos.', max_length=40, verbose_name='ID del objeto'),
        ),
    ]
