# Generated by Django 5.1.15 on 2026-09-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='ID del objeto'),
        ),
    ]
