# Generated by Django 5.1.15 on 2026-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attachment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.SlugField(blank=True, help_text='Identificador interno, sin espacios. Déjalo vacío: se genera solo a partir del Nombre.', unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactívalo para retirar este tipo sin borrar el historial de archivos que ya lo usan.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(help_text='Nombre tal como se va a mostrar, ej. «Acta de nacimiento» o «INE».', max_length=150, verbose_name='Nombre'),
        ),
    ]
