# Generated by Django 5.1.15 on 2026-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='considerado_para_reingreso',
            field=models.BooleanField(blank=True, default=None, help_text="Sin marcar mientras no se sepa — no forzar 'No' cuando el dato no se ha capturado.", null=True, verbose_name='Considerado para reingreso'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='solicitante_baja',
            field=models.CharField(blank=True, help_text='Quién levantó/solicitó la baja — mismo patrón que Posicion.solicitante_vacante.', max_length=150, verbose_name='Solicitante de baja'),
        ),
    ]
