# Generated by Django 5.1.15 on 2026-09-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_contrato_considerado_para_reingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='work_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de nómina'),
        ),
    ]
