# Generated by Django 5.1.15 on 2026-09-29 18:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_alter_empleado_work_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'base_manager_name': 'all_objects', 'ordering': ['-fecha_ingreso'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'base_manager_name': 'all_objects', 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelManagers(
            name='contrato',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='empleado',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
