# Generated by Django 5.1.15 on 2026-09-29 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_alter_contrato_options_alter_empleado_options_and_more'),
        ('positions', '0005_puesto_es_gerencia_de_unidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True), ('is_deleted', False)), fields=('empleado',), name='unique_contrato_vigente_por_empleado', violation_error_message='Este Empleado ya tiene un Contrato vigente — dale baja antes de crear uno nuevo.'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True), ('is_deleted', False)), fields=('posicion',), name='unique_contrato_vigente_por_posicion', violation_error_message='Esta Posición ya tiene un Contrato vigente — dale baja antes de asignar otro.'),
        ),
    ]
