# Generated by Django 5.1.15 on 2026-09-24 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('sabana_posiciones', 'Sábana — Posiciones'), ('colaboradores', 'Lista de Colaboradores'), ('horarios', 'Relación de Horarios')], max_length=30, verbose_name='Origen')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Archivo original')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de importación',
                'verbose_name_plural': 'Lotes de importación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HorarioRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('row_number', models.PositiveIntegerField(help_text='Número de fila original, para poder ir a verificarla en el archivo fuente.', verbose_name='Fila en el Excel')),
                ('data', models.JSONField(help_text='Encabezado original de la columna -> valor tal cual venía en la celda.', verbose_name='Datos crudos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='imports.importbatch', verbose_name='Lote de importación')),
            ],
            options={
                'verbose_name': 'Fila cruda — Horarios',
                'verbose_name_plural': 'Filas crudas — Horarios',
                'ordering': ['import_batch', 'row_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('row_number', models.PositiveIntegerField(help_text='Número de fila original, para poder ir a verificarla en el archivo fuente.', verbose_name='Fila en el Excel')),
                ('data', models.JSONField(help_text='Encabezado original de la columna -> valor tal cual venía en la celda.', verbose_name='Datos crudos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='imports.importbatch', verbose_name='Lote de importación')),
            ],
            options={
                'verbose_name': 'Fila cruda — Colaboradores',
                'verbose_name_plural': 'Filas crudas — Colaboradores',
                'ordering': ['import_batch', 'row_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosicionRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('row_number', models.PositiveIntegerField(help_text='Número de fila original, para poder ir a verificarla en el archivo fuente.', verbose_name='Fila en el Excel')),
                ('data', models.JSONField(help_text='Encabezado original de la columna -> valor tal cual venía en la celda.', verbose_name='Datos crudos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='imports.importbatch', verbose_name='Lote de importación')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fila cruda — Posiciones',
                'verbose_name_plural': 'Filas crudas — Posiciones',
                'ordering': ['import_batch', 'row_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawValueAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('domain', models.CharField(help_text='Qué tipo de dato es, ej. «puesto», «ubicacion», «nave», «area», «organization_node».', max_length=50, verbose_name='Dominio')),
                ('raw_value', models.CharField(help_text='Mayúsculas, sin acentos, sin espacios extra — así se busca al importar.', max_length=255, verbose_name='Valor crudo (normalizado)')),
                ('raw_value_original', models.CharField(blank=True, help_text='Cómo venía exactamente en el archivo — solo para referencia humana.', max_length=255, verbose_name='Valor crudo (tal cual)')),
                ('object_id', models.CharField(max_length=40, verbose_name='ID del destino')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Tipo de destino')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alias de valor crudo',
                'verbose_name_plural': 'Alias de valores crudos',
                'ordering': ['domain', 'raw_value'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'raw_value'), name='unique_raw_value_alias_per_domain')],
            },
        ),
    ]
