# Generated by Django 5.1.15 on 2026-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='file_checksum',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 del contenido exacto del archivo importado.', max_length=64, verbose_name='Checksum del archivo'),
        ),
    ]
