# Generated by Django 5.1.15 on 2026-09-24 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employment', '0004_alter_empleado_work_number'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, help_text='Identificador interno. Se genera solo a partir del Nombre.', unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.CharField(blank=True, help_text='Texto tal como lo maneja GPA, ej. «07:00 - 16:00» o varios rangos separados por «/».', max_length=255, verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Tipo de horario',
                'verbose_name_plural': 'Tipos de horario',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catorcena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de catorcena')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catorcena',
                'verbose_name_plural': 'Catorcenas',
                'ordering': ['anio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionUbicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_referencia', models.DateField(help_text='Fecha real conocida (ej. de registro en sistema) mientras no se resuelve la catorcena exacta.', verbose_name='Fecha de referencia')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_ubicacion', to='locations.area', verbose_name='Área')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ubicacion', to='employment.empleado', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('catorcena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_ubicacion', to='schedules.catorcena', verbose_name='Catorcena')),
            ],
            options={
                'verbose_name': 'Asignación de ubicación',
                'verbose_name_plural': 'Asignaciones de ubicación',
                'ordering': ['-fecha_referencia'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_referencia', models.DateField(help_text='Fecha real conocida (ej. de registro en sistema) mientras no se resuelve la catorcena exacta.', verbose_name='Fecha de referencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='employment.empleado', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('catorcena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_horario', to='schedules.catorcena', verbose_name='Catorcena')),
                ('tipo_horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='schedules.tipohorario', verbose_name='Tipo de horario')),
            ],
            options={
                'verbose_name': 'Asignación de horario',
                'verbose_name_plural': 'Asignaciones de horario',
                'ordering': ['-fecha_referencia'],
            },
        ),
        migrations.AddConstraint(
            model_name='catorcena',
            constraint=models.UniqueConstraint(fields=('numero', 'anio'), name='unique_catorcena_numero_anio'),
        ),
    ]
