# Generated by Django 5.1.15 on 2026-09-22 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Orden del nivel en la estructura, ej. «1» para Empresa.', unique=True, verbose_name='Número')),
                ('code', models.SlugField(help_text='Identificador interno sin espacios, ej. «unidad_negocio».', unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del nivel en español, ej. «Unidad de Negocio».', max_length=150, verbose_name='Nombre')),
                ('allows_recursive_nesting', models.BooleanField(default=False, help_text='Actívalo SOLO para el nivel que puede colgar de otro nodo de su propio mismo nivel, indefinidamente (ej. una Unidad de Negocio dentro de otra Unidad de Negocio: Gerencia de Operaciones → Departamento de Producción → Soldadura, todas el mismo nivel, solo cambia el nombre). Para el resto de los niveles, déjalo desmarcado.', verbose_name='Se anida a sí mismo')),
            ],
            options={
                'verbose_name': 'Nivel organizacional',
                'verbose_name_plural': 'Niveles organizacionales',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identificador corto, ej. «GPA».', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre completo, ej. «Grupo GPA».', max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Organización (Tenant)',
                'verbose_name_plural': 'Organización (Tenant)',
            },
        ),
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Identificador de negocio capturado manualmente, ej. «GPA-AZM-01».', max_length=50, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del nodo en español, ej. «Gerencia de Operaciones».', max_length=200, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el nodo sigue vigente, ej. desmárcalo al cerrar un departamento.', verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(help_text='Nivel que ocupa el nodo. Debe ser de un número mayor al del nodo padre elegido abajo — salvo en un nivel marcado como "se anida a sí mismo" (ej. Unidad de Negocio), que sí puede colgar de otro nodo de su mismo nivel.', on_delete=django.db.models.deletion.PROTECT, to='organizations.organizationallevel', verbose_name='Nivel organizacional')),
                ('parent', models.ForeignKey(blank=True, help_text='Nodo del que depende. Su nivel debe ser numéricamente menor al del nivel elegido arriba (o el mismo, si ese nivel se puede anidar a sí mismo); una Empresa no lleva padre.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organizations.organizationnode', verbose_name='Nodo padre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Se asigna sola — hoy solo existe «Grupo GPA».', on_delete=django.db.models.deletion.PROTECT, to='organizations.tenant', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Nodo organizacional',
                'verbose_name_plural': 'Nodos organizacionales',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('legal_name', models.CharField(help_text='Razón social completa, ej. «Azimatronics, S.A. de C.V.».', max_length=255, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, help_text='RFC de la empresa, ej. «AZI010203AB1»; puede dejarse vacío por ahora.', max_length=20, null=True, unique=True, verbose_name='RFC')),
                ('employer_registration', models.CharField(help_text='Registro patronal en texto libre, ej. «Y54-12345-10-1».', max_length=100, verbose_name='Registro patronal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('organization_node', models.OneToOneField(help_text='Nodo de nivel Empresa al que corresponde, ej. «GPA Azimatronics».', on_delete=django.db.models.deletion.PROTECT, to='organizations.organizationnode', verbose_name='Nodo organizacional')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationnode',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='unique_organization_node_code_per_parent'),
        ),
    ]
