# Generated by Django 5.1.15 on 2026-09-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationnode',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Se asigna sola — hoy solo existe «Grupo GPA».', on_delete=django.db.models.deletion.PROTECT, to='organizations.tenant', verbose_name='Organización'),
        ),
    ]
