# Generated by Django 5.1.15 on 2026-09-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationnode_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['code'], 'verbose_name': 'Organización (Tenant)', 'verbose_name_plural': 'Organización (Tenant)'},
        ),
    ]
