# Generated by Django 5.1.15 on 2026-09-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer_registration',
            field=models.CharField(blank=True, help_text='Registro patronal en texto libre, ej. «Y54-12345-10-1».', max_length=100, null=True, verbose_name='Registro patronal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Razón social completa, ej. «Azimatronics, S.A. de C.V.».', max_length=255, null=True, verbose_name='Razón social'),
        ),
    ]
